<?xml version="1.0"?>
<package format="2">
  <name>blasfeo_colcon</name>
  <version>0.0.0</version>
  <description>Colcon wrapper for Blasfeo.</description>

  <maintainer email="ruixiang.du@gmail.com">Ruixiang Du</maintainer>
  <maintainer email="rgrandia@ethz.ch">Ruben Grandia</maintainer>

  <license>See package</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
</package>
